# Generated by Django 3.1 on 2020-08-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
