# Generated by Django 3.1 on 2020-09-05 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/course/'),
            preserve_default=False,
        ),
    ]
